### ISSUE TITLE
argparser.h/args_help()

### ISSUE THREAD

**Issue by textbrowser** [maandree/argparser#15]
The prototype is missing its single parameter. Should the prototype be args_help(long use_colours)?

**Comment by maandree** [comment]
I'm planning to redo the API, but the parameter is missing from the prototype for backwards compatibility with older versions.

**Comment by textbrowser** [comment]
OK. Why not use getopt()?

**Comment by maandree** [comment]
I don't think it is as nice to to work with, especially
when working with options that may be used more
than once. Additionally argparser has some additional features:

If the option is --someting-very-long you can type --so
if there is no other option starting with --so.

I might add typo correction later on, so if you make
a small typo it can list suggestion on similarly spelled
options.

Variadic options: in `--v a b c d e f` all of a–f
are arguments for --v. All arguments after --v belong
to --v.

+options and ++options, for example +o and ++opt can
be added in addition to -o and --opt.

Similar to --, argparser has ++, which only stops the
next argument from being parsed as an option.

Later on I might add a function that outputs a
skeleton for an auto-auto-complete file.

argparser has a mechanism for printing the --help output,
this makes it easy to customise how you want it to look
for all programs that uses argparser.

**Comment by textbrowser** [comment]
Will you be reusing any of the current C source?

If so, please change line 1639 (char c) in argparser.c to int c.
